# Generated by Django 5.1.6 on 2025-03-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='established_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
