# Generated by Django 5.1.6 on 2025-03-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_established_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='established_date',
            new_name='established_year',
        ),
    ]
