# Generated by Django 5.1.6 on 2025-04-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
