# Generated by Django 5.1.6 on 2025-04-12 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_industry_state_job_job_type_job_industry_job_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='city',
        ),
    ]
